
on:
    pull_request:
        paths:
            - 'OpenAMASE/**'
    push:
        paths:
            - 'OpenAMASE/**'
    schedule:
        - cron: '45 3 * * 4'
    workflow_dispatch:

name: Build OpenAMASE
jobs:
    build:
        strategy:
            fail-fast: false
	    matrix:
     		env:[os:ubuntu-22.04, os:ubuntu-24.04]
                component:[amase]
                qualifier:[scenario=release]
        runs-on:${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v4
              with:
                  path: OpenAMASE

            - name: Set up java
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Build OpenAMASE
              run: |
                  cd OpenAMASE
                  ant jar
